# This is a workflow to help you run all JMeter scripts with Actions, and save Test Results as artifact
name: jmeter_test_results

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      user_number:
        description: "Number of Users"
        required: true
        default: "10"
      ramp_time:
        description: "Ramp-up Time (in seconds)"
        required: true
        default: "10"
      max_time:
        description: "Maximum Test Duration (in iterations)"
        required: true
        default: "1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Verify Repository Files
        run: |
           echo "Workspace Files:"
           ls -al

      - name: Create Test Report Directory
        run: mkdir -p $GITHUB_WORKSPACE/test_report

      # Install JMeter
      - name: Install JMeter
        run: |
          java -version
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.zip
          unzip apache-jmeter-5.6.3.zip
          cd apache-jmeter-5.6.3/bin
          ./jmeter -v

      - name: Install JMeter Plugins
        run: |
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.3
          wget -q --no-check-certificate https://jmeter-plugins.org/files/packages/jpgc-dummy-0.4.zip -P .
          unzip -o jpgc-dummy-0.4.zip && rm jpgc-dummy-0.4.zip

      - name: Run JMX Scripts with Parameters
        run: |
          cd $GITHUB_WORKSPACE
          for i in $(ls -A1 *.jmx); do
            echo "Running JMeter script: $i"
            cd $GITHUB_WORKSPACE/apache-jmeter-5.6.3/bin
            mkdir $GITHUB_WORKSPACE/test_report/${i%.jmx}
            ./jmeter -n -t $GITHUB_WORKSPACE/$i \
              -l $GITHUB_WORKSPACE/${i%.jmx}.jtl \
              -Juser_number=${{ inputs.user_number }} \
              -Jramp_time=${{ inputs.ramp_time }} \
              -Jmax_time=${{ inputs.max_time }} \
              -e -o $GITHUB_WORKSPACE/test_report/${i%.jmx}
          done

      - name: Move JTL Files to Test Report
        run: mv $GITHUB_WORKSPACE/*.jtl $GITHUB_WORKSPACE/test_report

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test_results
          path: test_report
