name: jmeter_test_results

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      user_number:
        description: "Number of Concurrent Users"
        required: true
        default: "10"
      ramp_time:
        description: "Ramp-up Time (in seconds)"
        required: true
        default: "10"
      max_time:
        description: "Maximum Test Iterations"
        required: true
        default: "1"

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Workflow Inputs
        run: |
          echo "Inputs:"
          echo "User Number: ${{ inputs.user_number }}"
          echo "Ramp Time: ${{ inputs.ramp_time }}"
          echo "Max Time: ${{ inputs.max_time }}"

      - name: Verify Workspace
        run: ls -al $GITHUB_WORKSPACE

      - name: Create Test Report Directory
        run: mkdir -p $GITHUB_WORKSPACE/test_report

      - name: Install JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.zip
          unzip apache-jmeter-5.6.3.zip
          mv apache-jmeter-5.6.3 $GITHUB_WORKSPACE/apache-jmeter

      - name: Run JMeter Test
        run: |
          echo "Running JMeter script pos.jmx from pos_jmeter directory"
          $GITHUB_WORKSPACE/apache-jmeter/bin/jmeter -n -t $GITHUB_WORKSPACE/pos_jmeter/pos.jmx \
            -l $GITHUB_WORKSPACE/test_report/pos.jtl \
            -Juser_number=${{ inputs.user_number }} \
            -Jramp_time=${{ inputs.ramp_time }} \
            -Jmax_time=${{ inputs.max_time }} \
            -e -o $GITHUB_WORKSPACE/test_report/pos

      - name: Verify Test Report Files
        run: |
          ls -al $GITHUB_WORKSPACE/test_report

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v3
        with:
          name: pos_jmeter_test_results
          path: pos_jmeter/test_report
